name: Docker Image CI

on:
  push:
    paths:
    - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: My first step
      uses: docker://alpine:3.8
