name: Docker Image CI

on:
  push:
    # paths:
    # - '*.md'

jobs:
  vale-lint-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: ./.github/actions/vale
      name: vale
      with:
        fileGlob: '*.{md}'
