name: Docker Image CI

on:
  push:
    # paths:
    # - '*.md'

jobs:
  vale-lint-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    # - uses: gaurav-nelson/github-action-vale-lint@v0.0.3
    #   env:
    #     GH_COMMENT_TOKEN: ${{ secrets.GH_COMMENT_TOKEN }}
    - uses: ./.github/actions/vale
      name: vale
      with:
        fileGlob: '*.{md}'
